spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inventory-service
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  application:
    name: inventory-service

server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
